### PR TITLE
Rewrite the UnrankableFinisherCheck and also add a TaikoUtils class

### LINKED ISSUE #5: refactor/rework the unrankable finishers check
current issues:
- very old check and its code is certainly flawed, could really benefit from a revision
- check only works reliably on kantan, futsuu, and muzu difficulties, oni and inner portion really need a rework
- finisher and preceding note same color detection is missing

### PR DESCRIPTION
**Pull request by hongaaronc**
## Summary
Resolves #5 

This PR fixes all the issues with the `UnrankableFinishersCheck`.

## Approach
Added a utility class (`TaikoUtils.cs`) which has a bunch of easy methods for checking a note's relationship to a pattern:
* `IsDon()`
* `IsFinisher()`
* `IsAtBeginningOfPattern()`
* `IsAtEndOfPattern()`
* `IsInMiddleOfPattern()` (unused currently)
* `IsNotInPattern()` (unused currently)
* `GetPatternSpacingMs()`

These methods are implemented by following this logic:
1. Look to the previous and next adjacent notes
2. Get the spacing between previous and adjacent
3. Lower spacing side = part of the same pattern (so beginning or end)
4. Same spacing = middle of pattern

For the actual check, I've added several dictionaries to define the first snap divisor that counts as a violation in various cases, with a Problem severity version and a Warning severity version:
* `maximalGapBeats` : Triggered if the pattern is <= this snap divisor regardless of any other conditions
* `maximalGapBeatsRequiringColorChangeBefore` : Triggered if note doesn't have a color change before it and isn't the first note, and the pattern is <= this snap divisor
* `maximalGapBeatsRequiringColorChangeAfter` : Triggered if note doesn't have a color change in the note after it and isn't the last note, and the pattern is <= this snap divisor
* `maximalGapBeatsRequiringFinalNote` : Triggered if note is the final note in the pattern, and the pattern is <= this snap divisor

## Testing
* Seems to work from everything I've tested. No known issues atm but feel free to test

### CODE REVIEW

**Review by Hiviexd — APPROVED** [review]
did a code pass + some testing, everything is working well, thanks!!

also, i was debating whether to lower the muzu threshold from 1/4 to 1/3, considering that we treat 1/3 patterning similarly to 1/4 in terms of difficulty, but that'd mark 1/3 dK and kD as unrankable, which they arguably can be fine? so mayb it's fine to keep as-is?

would like to hear your thoughts before merging

**Comment by hongaaronc** [comment]
Maybe we could add 1/3 Muzu as a warning. Probably wouldn't do problem tho, since I think 1/3 finisher might make sense for some swing or 6/8 songs.

**Comment by hongaaronc** [comment]
Not ranked but I could see 1/3 + finisher being used like how I did in Muzu here. This is very low BPM though and 1/3 is practically used like how 1/2 would normally be:
https://osu.ppy.sh/beatmapsets/1856271

Btw... on the note of slower BPM songs, should https://github.com/Hiviexd/MVTaikoChecks/blob/cab8008e4ca065d356311b16a2345fe8ff10e5ef/Checks/Compose/UnrankableFinisherCheck.cs#L184 use `timing.GetNormalizedMsPerBeat()` instead of `timing.msPerBeat` - to add BPM scaling?

I wasn't sure but I guess thinking about it more, I think it should probably?

**Comment by Hiviexd** [comment]
probably a good idea to consider bpm scaling for this

**Comment by hongaaronc** [comment]
Ok added both the BPM scaling and 1/3 + finisher warning.

**Pull request merged**
